# Generated by Django 6.0.3 on 2026-03-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageapp', '0002_prettynum_alter_userinfo_depart_alter_userinfo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
    ]
